services:
  web:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=userdb
      - DB_USER=admin
      - DB_PASS=admin123
    networks:
      - app-network
    volumes:
      - ./logs:/app/logs  # Bind mount to persist logs to the host machine
    deploy:
      replicas: 3  # Scale the web application to 3 instances
      restart_policy:
        condition: on-failure

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data: